### ISSUE TITLE
好棒的插件，能不能向高版本移植一下（）

### ISSUE THREAD

**Issue by kukemc** [hank9999/AtPlayer#1]
经测试 1.20.4 上功能运行良好，但是玩家一说话就会提示没有权限 不@还是不@都会提示（）
![image](https://github.com/hank9999/AtPlayer/assets/95417077/59648c27-0d32-4303-9be5-51d697994dce)

**Comment by hank9999** [comment]
感谢支持，我去测试一下

**Comment by hank9999** [comment]
@kukemc 我刚才测试了一下 是因为 `AtPlayer.use` 权限默认OP才有, 如果想要普通玩家使用, 你需要在权限管理插件中添加 `AtPlayer.use` 权限

**Comment by hank9999** [comment]
v1.1.1(939952e) 已修复判断逻辑问题导致的没权限刷屏

**Comment by hank9999** [comment]
v1.1.1(939952e) 已修复判断逻辑问题导致的没权限刷屏, 麻烦再试一下（ @kukemc

**Comment by kukemc** [comment]
> v1.1.1([939952e](https://github.com/hank9999/AtPlayer/commit/939952e01ace28151dac3f1cda79417595125a57)) 已修复判断逻辑问题导致的没权限刷屏, 麻烦再试一下（ @kukemc

OKOK 十分感谢，我现在就开mc试试

**Comment by kukemc** [comment]
![image](https://github.com/hank9999/AtPlayer/assets/95417077/af427a36-294a-43bf-8130-d675d167fa06)
没问题了 谢谢大佬
